CREATE TABLE Company
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_company_id BIGINT,
    CONSTRAINT fk_parent_id
        FOREIGN KEY(parent_company_id)
            REFERENCES Company(id)
        ON DELETE CASCADE
);
